### ISSUE TITLE
How to dedup schemas?

### ISSUE THREAD

**Issue by nappa85** [tamasfe/aide#27]
If you take a look at [my example project](https://github.com/nappa85/openapi_axum), it generates 26 times the same schema for `Foo`.
The behavior I would expect is to generate a single schema for Foo in /components/schemas and then use `$ref` to use it.
Looking at the code, I see the opportunity in ReferenceOr::Reference, but I can't find a place to generate it, the code always uses the other variant

**Comment by tamasfe** [comment]
You can enable that behaviour with `gen::extract_schemas`.

https://github.com/tamasfe/aide/blob/556227c330481f960e99e9ee3889cf06a09965d4/crates/aide/src/gen.rs#L54

It's disabled by default because `schemars` does no name mangling nor detects collisions so `foo::Foo` will be overwritten by `bar::Foo`.

**Comment by nappa85** [comment]
Thank you

Il gio 8 dic 2022, 17:16 Ferenc Tamás ***@***.***> ha scritto:
