### ISSUE TITLE
Parameters are not generated correctly

### ISSUE THREAD

**Issue by niklas-stegmann** [tamasfe/aide#4]
If parameters are used in the URL, they are not generated correctly in OpenAPI-Spec.

Current: (from [example](https://github.com/tamasfe/aide/tree/master/examples/example-axum))
![image](https://user-images.githubusercontent.com/32418474/195985198-b6f09278-5bf8-42b6-87fd-ca325c5d6265.png)

Expected: (from https://redocly.github.io/redoc/#tag/store/operation/getOrderById)
![image](https://user-images.githubusercontent.com/32418474/195985258-4001b076-7c1a-4e85-99c3-b18db586c97b.png)

**Comment by tamasfe** [comment]
Can you share the code the code used to generate the spec?

Parameters are purely based on extractors right now, just having `:id` in the path will not show up.

**Comment by tamasfe** [comment]
Just published `0.6.2`, it should work as expected.

**Comment by niklas-stegmann** [comment]
Thank you! Can confirm that it works.

**Comment by sminez** [comment]
In the example the parameter being extracted is wrapped in a struct that derives `JsonSchema` ([here](https://github.com/tamasfe/aide/blob/master/examples/example-axum/src/todos/routes.rs#L87-L91)). Is this required in order to get path parameters to be generated correctly? I've got a number of endpoints that just need to accept a `String` but using what works fine for axum (`Path(my_param): Path<String>`) still results in the `{my_param}` style output originally reported.

**Comment by tamasfe** [comment]
Yes, it is required, otherwise aide has no information about the parameter, not even the parameter name. In theory the name could be parsed from the path, but we don't do that in the current implementation.
