### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by javihc** [tamasfe/aide#85]
After using aide for generating the OpenApi doc for an API the memory consumption has increased from a couple of megabytes to more than a gigabyte. Is it my problem or aide use a lot of RAM?

**Comment by 0xdeafbeef** [comment]
Maybe #48 is related?

**Comment by tamasfe** [comment]
We've been using `aide` in production for a while now and haven't observed any leaks, although without redoc. The API document should be generated only once, how you serve it afterwards is up to you (the examples in the docs are inefficient for the sake of simplicity).

Feel free to reopen this once it is confirmed that the issue is with `aide` and/or you have a reproducible example.

**Comment by Wicpar** [comment]
Hello, so actually i pinpointed the ram usage issue exactly to aide, but not exactly the crate. Turns out it is absolutely imperative to wrap the `OpenAPI` struct when used in an extension extension with an arc, else it will be cloned for every single connection.
